source "https://rubygems.org"

domain_logic_absolute_path = File.dirname(__FILE__) + "/components/domain_logic"
gem 'domain_logic', path: domain_logic_absolute_path

# Declare your gem's dependencies in admin_ui.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
local_gemspec = File.dirname(__FILE__) + "/components/admin_ui"
gemspec path: local_gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
